# Generated by Django 5.1.6 on 2025-03-08 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_market', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RenameField(
            model_name='market',
            old_name='image',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_number1',
            new_name='phone_number',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number2',
        ),
        migrations.AddField(
            model_name='book',
            name='age_restriction',
            field=models.CharField(choices=[('детский', 'детский'), ('взрослый', 'взрослый')], default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='book_market.genre'),
        ),
        migrations.AlterField(
            model_name='book',
            name='released_date',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(2025)]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(110)]),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
