# Generated by Django 5.1.6 on 2025-03-12 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_market', '0005_alter_subscription_options_market_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_branches', to='book_market.market'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_contacts', to='book_market.market'),
        ),
    ]
