# Generated by Django 5.1.6 on 2025-03-15 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_market', '0008_userprofile_profile_image_alter_market_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='book_market.favorite'),
        ),
    ]
